"""init

Revision ID: 0499beea0b7c
Revises: 
Create Date: 2026-05-21 01:13:45.535657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0499beea0b7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_detected', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sentiment_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emotion_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('analysis_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('topic_keywords', sa.String(length=200), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('topic_keywords')
        batch_op.drop_column('analysis_confidence')
        batch_op.drop_column('emotion_label')
        batch_op.drop_column('sentiment_label')
        batch_op.drop_column('language_detected')

    op.drop_table('password_reset_tokens')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
